# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizmaster
    username: root
    password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

## Security configuration (optional)
#spring:
#  security:
#    user:
#      name: user
#      password: password
